Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AcademicManagement.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Controllers/CategoriesController.cs
using AcademicManagement.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AcademicManagement.FactoryMethod;
using AcademicManagement.Models;
using Microsoft.EntityFrameworkCore;

namespace AcademicManagement.Controllers
{
    public class CategoriesController : CategoriesFactory
    {
        public CategoriesController(AcademicContext context) : base(context)
        {
            base.context = context;
        }

        // GET: Category
        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (name == null)
                {
                    return View(ViewAll().ToList());
                }
                else
                {
                    return View(SearchByName(name));
                } 
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Category/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var category = SearchById(id);
                if (category == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(category);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Description")] Category category)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    AddNew(category);
                    return RedirectToAction(nameof(Index));
                }
                return View(category);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET:  Category/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var category = SearchById(id);
                if (category == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(category);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST:  Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description")] Category category)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (id != category.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        EditModel(category);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CategoryExists(category.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(category);
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool CategoryExists(int id)
        {
            return (SearchById(id) != null);
        }

        // GET:  Category/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var category = SearchById(id);
                if (category == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(category);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST:  Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var category = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
    }
}

Controllers/CoursesController.cs
using AcademicManagement.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;

namespace AcademicManagement.Controllers
{
    public class CoursesController : CoursesFactory
    {
        public CoursesController(AcademicContext context): base(context)
        {
            this.context = context;
        }

        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (name == null)
                {
                    return View(ViewAll());
                }
                else
                {
                    return View(SearchByName(name));
                }
            }
            return RedirectToAction("Index", "NotFound");
        }

        public IActionResult Create()
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainees = this.context.Trainees.ToList();
                var categories = this.context.Categories.ToList();
                dynamic models = new ExpandoObject();
                models.Trainees = trainees;
                models.Categories = categories;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Assign(int[] listId, string Name, int CategoryId, string Description)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var categories = this.context.Categories.ToList();
                var course = new Course();
                course.Name = Name;
                course.Description = Description;
                course.Category = categories.Find(item => item.Id == CategoryId);
                AddNewTraineeCourse(listId, course);
                AddNew(course);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = SearchById(id);
                var categories = this.context.Categories.ToList();
                var trainees = this.context.Trainees.ToList();
                course.TraineeCourses.ToList().ForEach(item =>
                {
                    trainees.Remove(item.Trainee);
                });
                dynamic models = new ExpandoObject();
                models.CourseTrainees = course.TraineeCourses;
                models.Trainees = trainees;
                models.Categories = categories;
                models.Course = course;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int courseId, int[] listId, string Name, int CategoryId, string Description)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = this.context.Courses.ToList().Find(item => item.Id == courseId);
                var categories = this.context.Categories.ToList();
                DeleteTraineeCourses(courseId);
                AddNewTraineeCourse(listId, course);
                course.Name = Name;
                course.Category = categories.Find(item => item.Id == CategoryId);
                course.Description = Description;
                EditModel(course);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = SearchById(id);
                return View(course);
            }
            return RedirectToAction("Index", "NotFound");
        }

        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = SearchById(id);
                return View(course);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
    }
}

Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademicManagement.Data;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;
using System.Dynamic;

namespace AcademicManagement.Controllers
{
	public class TopicsController : TopicFactory
	{
        public TopicsController(AcademicContext context) : base(context)
        {
            base.context = context;
        }

        // GET: Topic
        public IActionResult Index()
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainers = context.Trainers.ToList();
                var courses = context.Courses.ToList();
                var topics = ViewAll().ToList();
                dynamic models = new ExpandoObject();
                models.Trainers = trainers;
                models.Courses = courses;
                models.Topics = topics;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Topic/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                if (topic == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Description,Trainer,Course")] Topic topic, int courseId, int trainerId)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    topic.Trainer = this.context.Trainers.ToList().Find(item => item.Id == trainerId);
                    topic.Course = this.context.Courses.ToList().Find(item => item.Id == courseId);
                    AddNew(topic);
                    return RedirectToAction(nameof(Index));
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Topic/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                var trainers = context.Trainers.ToList();
                var courses = context.Courses.ToList();
                if (topic == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                dynamic models = new ExpandoObject();
                models.Trainers = trainers;
                models.Courses = courses;
                models.Topic = topic;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Topic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description,Trainer,Course")] Topic topic, int courseId, int trainerId)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (id != topic.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        topic.Course = context.Courses.ToList().Find(item => item.Id == courseId);
                        topic.Trainer = context.Trainers.ToList().Find(item => item.Id == trainerId);
                        EditModel(topic);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TraineeExists(topic.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Topic/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                if (topic == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Topic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool TraineeExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Views/Categories/Delete.cshtml
@model AcademicManagement.Models.Category
@{
    ViewData["Title"] = "Categories Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <div class="card">
        <div class="card-body">
            <div class="modal-body row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Category name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Description" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Description</label>
                    </div>
                </div>
                <div class="modal-footer">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Categories/Details.cshtml
@model AcademicManagement.Models.Category
@{
    ViewData["Title"] = "Categories Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <div>
        <div class="card">
            <div class="card-body">
                <div class="modal-body row">
                    <div class="col">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                            <label for="floatingInput" class="ml-5">Category name</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Description" class="form-control pl-4" id="floatingInput" disabled>
                            <label for="floatingInput" class="ml-5">Description</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Categories/Edit.cshtml
@model AcademicManagement.Models.Category

@{
    ViewData["Title"] = "Categories Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="card">
    <div class="card-body">
        <form method="post" asp-action="Edit" asp-controller="Categories">
            <div class="modal-body row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Category name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Description" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Description</label>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Categories/Index.cshtml
@model IEnumerable<AcademicManagement.Models.Category>
@{
    ViewData["Title"] = "Categories Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="margin-horizontal">
    <a class="link-secondary bold h4" asp-action="Index" asp-controller="Trainers">Trainer</a>
    <a class="link-secondary bold margin-left h4" asp-action="Index" asp-controller="Trainees">Trainee</a>
    <a class="link-primary bold margin-left h4" asp-action="Index" asp-controller="Courses">Course</a>
</div>

<div class="margin-horizontal">
    <a class="link-secondary bold h5" asp-action="Index" asp-controller="Topics">Topics</a>
    <a class="link-primary bold margin-left h5" asp-action="Index" asp-controller="Categories">Categories</a>
</div>

<h1>Index category</h1>

<div class="search_add">
    <a class="link-primary pointer pointer"
       data-bs-toggle="modal"
       data-bs-target="#createNewCategory">
        Create new Category
    </a>
    <form class="d-flex" method="get" asp-action="Index" asp-controller="Categories">
        <input class="form-control me-2" type="search" name="name" placeholder="Search" aria-label="Search">
        <input class="btn btn-outline-success" type="submit" />
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="createNewCategory" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Create new category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-action="Index" asp-controller="Categories">
                <div class="modal-body row">
                    <div class="col">
                        <div class="form-floating mb-3">
                            <input type="text" name="Name" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Category Name</label>
                        </div>
                    </div>

                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" name="Description" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Description</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-primary" value="Create" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>