Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademicManagement.Data;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;

namespace AcademicManagement.Controllers
{
    public class TraineesController : TraineesFactory
    {
        public TraineesController(AcademicContext context) : base(context) {
            base.context = context;
        }

        // GET: Trainees
        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if(name == null)
                {
                    return View(ViewAll().ToList());
                }
                else
                {
                    return View(SearchByName(name));
                }
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainees/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Age,Email,Password,Telephone,DateOfBirth,Education,MainProgrammingLanguage,TOEICScore,ExperienceDetails,Department,Location")] Trainee trainee)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    AddNew(trainee);
                    return RedirectToAction(nameof(Index));
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainees/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Trainees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Age,DateOfBirth,Education,MainProgrammingLanguage,TOEICScore,ExperienceDetails,Department,Location,Id,Email,Password,Name,Telephone")] Trainee trainee)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (id != trainee.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        EditModel(trainee);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TraineeExists(trainee.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainees/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Trainees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool TraineeExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Controllers/TrainerAccountController.cs
using AcademicManagement.Data;
using AcademicManagement.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;

namespace AcademicManagement.Controllers
{
	public class TrainerAccountController : Controller
	{
		private readonly AcademicContext _context;
        private IWebHostEnvironment _hostingEnvironment;

        public TrainerAccountController(AcademicContext context, IWebHostEnvironment environment)
		{
			_context = context;
            _hostingEnvironment = environment;
		}
        public IActionResult Index()
        {
            if (UserSingleton.getIntance().Role == new Trainer().GetType().Name)
            {
                string path = Path.Combine(_hostingEnvironment.WebRootPath, "avatars/" + UserSingleton.getIntance().Email + ".jpg");
                ViewBag.IsUpload = System.IO.File.Exists(path);

                var email = UserSingleton.getIntance().Email;
                var trainer = _context.Trainers.ToList().Find(m => m.Email == email);
                if (trainer != null)
                {
                    ViewBag.TrainerId = trainer.Id;
                    var courses = _context.Courses.ToList();
                    List<Course> listCourses = new List<Course>();
                    courses.ForEach(item =>
                    {
                        if (SearchCourseById(item.Id).Topics != null)
                        {
                            SearchCourseById(item.Id).Topics.ToList().ForEach(topic =>
                            {
                                if(topic.Trainer.Id == trainer.Id)
                                {
                                    if(listCourses.Find(c => c.Id == item.Id) == null)
                                    {
                                        listCourses.Add(SearchCourseById(item.Id));
                                    }
                                }
                            });
                        }
                    });

                    return View(listCourses);
                }
                return View();
            }
            return RedirectToAction("Index", "NotFound");
        }
        public IActionResult Profile()
		{
			if(UserSingleton.getIntance().Role == new Trainer().GetType().Name)
            {
                string path = Path.Combine(_hostingEnvironment.WebRootPath, "avatars/" + UserSingleton.getIntance().Email + ".jpg");
                ViewBag.IsUpload = System.IO.File.Exists(path);

                var email = UserSingleton.getIntance().Email;
                var trainer = _context.Trainers.ToList().Find(m => m.Email == email);
                if (trainer != null)
                {
                    return View(trainer);
                }
                return View();
            }
            return RedirectToAction("Index", "NotFound");
        }
        public IActionResult Edit()
        {
            if (UserSingleton.getIntance().Role == new Trainer().GetType().Name)
            {
                var email = UserSingleton.getIntance().Email;
                var currentTrainer = _context.Trainers.ToList().Find(e => e.Email == email);
                return View(currentTrainer);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(IFormFile file, [Bind("Id,Name,Email,Password,Telephone,WorkingPlace,Type")] Trainer trainer)
        {
            if (UserSingleton.getIntance().Role == new Trainer().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        if (file != null)
                        {
                            string uploads = Path.Combine(_hostingEnvironment.WebRootPath, "avatars");

                            if (file.Length > 0)
                            {
                                string fileName = UserSingleton.getIntance().Email + ".jpg";
                                string filePath = Path.Combine(uploads, fileName);
                                using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                                {
                                    file.CopyTo(fileStream);
                                }
                            }
                        }
                        //var email = UserSingleton.getIntance().Email;
                        //var id = _context.Trainers.ToList().Find(e => e.Email == email).Id;
                        //trainer.Id = id;
                        _context.Update(trainer);  
                        _context.SaveChanges();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TrainerExists())
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Profile));
                }
                return View(trainer);
            }
            return RedirectToAction("Index", "NotFound");
        }
        private bool TrainerExists()
        {
            var email = UserSingleton.getIntance().Email;
            return (_context.Trainers.ToList().Find(e => e.Email == email) != null);
        }
        public Course SearchCourseById(int id)
        {
            var courseTrainees = _context.CourseTrainees.ToList().FindAll(item => item.CourseId == id);
            var topics = _context.Topics.ToList();
            var trainees = _context.Trainees.ToList();
            var trainers = _context.Trainers.ToList();
            var course = _context.Courses.ToList().Find(item => item.Id == id);
            var category = _context.Categories.ToList().Find(item => item.Id == course.Category.Id);

            if (course.Topics != null)
            {
                course.Topics.ToList().ForEach(item =>
                {
                    item = topics.Find(topic => topic.Id == item.Id);
                    item.Trainer = trainers.Find(trainer => trainer.Id == item.Trainer.Id);
                });
            }

            courseTrainees.ForEach(item =>
            {
                var traineeInCourse = trainees.Find(trainee => trainee.Id == item.TraineeId);
                item.Trainee = traineeInCourse;
            });
            course.TraineeCourses = courseTrainees;
            course.Category = category;
            return course;
        }
    }
}

Views/TrainerAccount/Edit.cshtml
@model AcademicManagement.Models.Trainer

@{
    ViewData["Title"] = "Edit Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Trainee</h1>

<div class="margin-horizontal">
    <a class="link-secondary bold h4" asp-action="Index">Schedule</a>
    <a class="link-secondary bold margin-left h4" asp-action="Profile">Profile</a>
    <a class="link-primary bold margin-left h4" asp-action="Edit">Edit Profile</a>
</div>

<div class="card">
    <div class="card-body">
        <form method="post" asp-action="Edit" asp-controller="TrainerAccount" enctype="multipart/form-data">
            <div class="modal-body row">
                <div class="">
                    <div class="form-floating mb-3">
                        @Html.TextBox("file", "", new { type = "file" })
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Email" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Email</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Password" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Password</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="tel" asp-for="Telephone" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Telephone</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="WorkingPlace" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">WorkingPlace</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Type" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Type</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" asp-for="Id"/>
                <button asp-action="Index" type="button" class="btn btn-secondary">Back to list</button>
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/TrainerAccount/Index.cshtml
@model IEnumerable<AcademicManagement.Models.Course>
@{ 
    ViewData["Title"] = "Schedule";
}
<div class="container-lg">
    <h1>Schedule</h1>
    <div class="margin-horizontal">
        <a class="link-primary bold h4" asp-action="Index">Schedule</a>
        <a class="link-secondary bold margin-left h4" asp-action="Profile">Profile</a>
        <a class="link-secondary bold margin-left h4" asp-action="Edit">Edit Profile</a>
    </div>
    @foreach (Course item in Model)
    {
        <div class="shadow-sm course-border p-5 mt-3">
            <div class="name_course_X">
                <div class="name_course">
                    <h3>@item.Name</h3> 
                </div>
            </div>
            <div class="course-container">
                <div class="course-info-container">
                    @if (item.Topics != null)
                    {
                        @foreach (Topic topic in item.Topics)
                        {
                            @if (topic.Trainer.Id == ViewBag.TrainerId)
                            {
                                <div class="topic-container">
                                    <div>
                                        <p>Topic: @topic.Name </p>
                                    </div>
                                </div>
                            }
                        }
                    }
                </div>
            </div>
        </div>
    }
</div>

Views/TrainerAccount/Profile.cshtml
@model AcademicManagement.Models.Trainer
@{
    ViewData["Title"] = "Trainer Profile";
    var email = UserSingleton.getIntance().Email;
    var imageLink = "/avatars/" + email + ".jpg";
}

<div class="card m-5">
    <div class="card-body">
        <div class="margin-horizontal">
            <a class="link-secondary bold h4" asp-action="Index">Schedule</a>
            <a class="link-primary bold margin-left h4" asp-action="Profile">Profile</a>
            <a class="link-secondary bold margin-left h4" asp-action="Edit">Edit Profile</a>
        </div>
        <form method="post" asp-action="Edit" asp-controller="Trainees">
            <div class="modal-body row">
                <h4>My Account</h4>
                <div class="">
                    <div class="profile-card">
                        @if (ViewBag.IsUpload)
                        {
                            <img src="@imageLink" class="img-thumbnail cover-photo" alt="..." height="120" width="120">
                        }
                        else
                        {
                            <img src="/images/images.png" class="img-thumbnail cover-photo" alt="..." height="120" width="120">
                        }
                        <div class="profile-name">@Html.DisplayFor(model => model.Name)</div>
                    </div>
                </div>
                <br />
                <p>View and edit your personal info below</p>
                <hr />
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Email" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Email</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Password" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Password</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="tel" asp-for="Telephone" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Telephone</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="WorkingPlace" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">WorkingPlace</label>
                    </div>
                </div>
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Type" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Type</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a asp-action="Edit" class="btn btn-primary">Edit</a>
            </div>
        </form>
    </div>
</div>