Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AcademicManagement.Models
{
    public class Trainer: Person
    {
        public string WorkingPlace { get; set; }
        public string Type { get; set; }
    }
}

Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AcademicManagement.Data;
using AcademicManagement.FactoryMethod;
using AcademicManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AcademicManagement.Controllers
{
    public class AdminsController : AdminsFactory
    {
        public AdminsController(AcademicContext context): base(context)
        {
            base.context = context;
        }
        // GET: Admin
        public IActionResult Index()
        {
            if(UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                return View(ViewAll().ToList());
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Admin/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var Admin = SearchById(id);
                if (Admin == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(Admin);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Email,Password,Telephone")] Admin Admin)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    AddNew(Admin);
                    return RedirectToAction(nameof(Index));
                }
                return View(Admin);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET:  Admin/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var Admin = SearchById(id);
                if (Admin == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(Admin);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST:  Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Email,Password,Name,Telephone")] Admin Admin)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (id != Admin.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        EditModel(Admin);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!AdminExists(Admin.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(Admin);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET:  Admin/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                return View(trainee);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST:  Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var Admin = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        private bool AdminExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademicManagement.Data;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;

namespace AcademicManagement.Controllers
{
    public class StaffsController : StaffFactory
    {
        public StaffsController(AcademicContext context) : base(context)
        {
            base.context = context;
        }

        // GET: Staff
        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (name == null)
                {
                    return View(ViewAll().ToList());
                }
                else
                {
                    return View(SearchByName(name));
                }
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Staff/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var staff = SearchById(id);
                if (staff == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(staff);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Email,Password,Telephone")] Staff staff)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    AddNew(staff);
                    return RedirectToAction(nameof(Index));
                }
                return View(staff);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET:  Staff/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var staff = SearchById(id);
                if (staff == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(staff);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST:  Staff/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Email,Password,Name,Telephone")] Staff staff)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (id != staff.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        EditModel(staff);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!StaffExists(staff.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(staff);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET:  Staff/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST:  Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var staff = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool StaffExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademicManagement.Data;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;

namespace AcademicManagement.Controllers
{
    public class TrainersController : TrainersFactory
    {
        public TrainersController(AcademicContext context) : base(context)
        {
            base.context = context;
        }

        // GET: Trainers
        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if(UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (name == null)
                {
                    return View(ViewAll().ToList());
                }
                else
                {
                    return View(SearchByName(name));
                }
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainers/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var trainer = SearchById(id);
                if (trainer == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainer);
            }
            return RedirectToAction("Index","NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Email,Password,Telephone,WorkingPlace,Type")] Trainer trainer)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    AddNew(trainer);
                    return RedirectToAction(nameof(Index));
                }
                return View(trainer);   
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainers/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var trainer = SearchById(id);
                if (trainer == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainer);
            }
            return RedirectToAction("Index", "NotFound");      
        }

        // POST: Trainers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Email,Password,Telephone,WorkingPlace,Type")] Trainer trainer)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                if (id != trainer.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        EditModel(trainer);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TrainerExists(trainer.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(trainer);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainers/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var trainer = SearchById(id);
                if (trainer == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainer);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Trainers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name || UserSingleton.getIntance().Role == new Admin().GetType().Name)
            {
                var trainer = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool TrainerExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Views/Trainers/Delete.cshtml
@model AcademicManagement.Models.Trainer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete trainer</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <div class="card">
        <div class="card-body">
            <div class="modal-body row">
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Email" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Email</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="password" asp-for="Password" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Password</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="tel" asp-for="Telephone" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Telephone</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="WorkingPlace" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Working place</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Type" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Type</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

Views/Trainers/Details.cshtml
@model AcademicManagement.Models.Trainer

@{
    ViewData["Title"] = "Trainers Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details trainer</h1>

<div>
    <div class="card">
        <div class="card-body">
            <div class="modal-body row">
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Email" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Email</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Password" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Password</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="tel" asp-for="Telephone" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Telephone</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="WorkingPlace" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Working place</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Type" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Type</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            </div>
        </div>
    </div>
</div>

Views/Trainers/Edit.cshtml
@model AcademicManagement.Models.Trainer

@{
    ViewData["Title"] = "Trainers Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Trainee</h1>

<div class="card">
    <div class="card-body">
        <form method="post" asp-action="Edit" asp-controller="Trainers">
            <div class="modal-body row">
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Email" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Email</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Password" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Password</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="tel" asp-for="Telephone" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Telephone</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="WorkingPlace" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Working place</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Type" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Type</label>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Trainers/Index.cshtml
@model IEnumerable<AcademicManagement.Models.Trainer>

@{
    ViewData["Title"] = "Trainers Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (UserSingleton.getIntance().Role == new Admin().GetType().Name)
{
    <div class="margin-horizontal">
        <a class="link-secondary bold h4" asp-action="Index" asp-controller="Admins">Admins</a>
        <a class="link-secondary bold margin-left h4" asp-action="Index" asp-controller="Staffs">Staffs</a>
        <a class="link-primary bold margin-left h4" asp-action="Index" asp-controller="Trainers">Trainers</a>
    </div>
}
else
{
    <div class="margin-horizontal">
        <a class="link-primary bold h4" asp-action="Index" asp-controller="Trainers">Trainer</a>
        <a class="link-secondary bold margin-left h4" asp-action="Index" asp-controller="Trainees">Trainee</a>
        <a class="link-secondary bold margin-left h4" asp-action="Index" asp-controller="Courses">Course</a>
    </div>
}


<h1>Trainer management</h1>

<div class="search_add">
    <a class="link-primary pointer"
       data-bs-toggle="modal"
       data-bs-target="#createNewTrainer">
        Create new trainee account
    </a>
    <form class="d-flex" method="get" asp-action="Index" asp-controller="Trainers">
        <input class="form-control me-2" type="search" name="name" placeholder="Search" aria-label="Search">
        <input class="btn btn-outline-success" type="submit" />
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>
            <th>
                @Html.DisplayName("Working place")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telephone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkingPlace)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="createNewTrainer" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="createNewTrainerLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createNewTrainerLabel">Create new trainer account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-action="Index" asp-controller="Trainers">
                <div class="modal-body">
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" name="Name" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Full name</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="email" name="Email" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Email</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" name="Password" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Password</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="tel" name="Telephone" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Telephone</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" name="Type" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Type (Internal/External)</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" name="WorkingPlace" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Working place</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>