Models/Topic.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AcademicManagement.Models
{
    public class Topic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Trainer Trainer { get; set; }
        public Course Course { get; set; }
    }
}

Controllers/CoursesController.cs
using AcademicManagement.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;

namespace AcademicManagement.Controllers
{
    public class CoursesController : CoursesFactory
    {
        public CoursesController(AcademicContext context): base(context)
        {
            this.context = context;
        }

        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (name == null)
                {
                    return View(ViewAll());
                }
                else
                {
                    return View(SearchByName(name));
                }
            }
            return RedirectToAction("Index", "NotFound");
        }

        public IActionResult Create()
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainees = this.context.Trainees.ToList();
                var categories = this.context.Categories.ToList();
                dynamic models = new ExpandoObject();
                models.Trainees = trainees;
                models.Categories = categories;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Assign(int[] listId, string Name, int CategoryId, string Description)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var categories = this.context.Categories.ToList();
                var course = new Course();
                course.Name = Name;
                course.Description = Description;
                course.Category = categories.Find(item => item.Id == CategoryId);
                AddNewTraineeCourse(listId, course);
                AddNew(course);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = SearchById(id);
                var categories = this.context.Categories.ToList();
                var trainees = this.context.Trainees.ToList();
                course.TraineeCourses.ToList().ForEach(item =>
                {
                    trainees.Remove(item.Trainee);
                });
                dynamic models = new ExpandoObject();
                models.CourseTrainees = course.TraineeCourses;
                models.Trainees = trainees;
                models.Categories = categories;
                models.Course = course;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int courseId, int[] listId, string Name, int CategoryId, string Description)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = this.context.Courses.ToList().Find(item => item.Id == courseId);
                var categories = this.context.Categories.ToList();
                DeleteTraineeCourses(courseId);
                AddNewTraineeCourse(listId, course);
                course.Name = Name;
                course.Category = categories.Find(item => item.Id == CategoryId);
                course.Description = Description;
                EditModel(course);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = SearchById(id);
                return View(course);
            }
            return RedirectToAction("Index", "NotFound");
        }

        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var course = SearchById(id);
                return View(course);
            }
            return RedirectToAction("Index", "NotFound");
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }
    }
}

Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademicManagement.Data;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;
using System.Dynamic;

namespace AcademicManagement.Controllers
{
	public class TopicsController : TopicFactory
	{
        public TopicsController(AcademicContext context) : base(context)
        {
            base.context = context;
        }

        // GET: Topic
        public IActionResult Index()
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainers = context.Trainers.ToList();
                var courses = context.Courses.ToList();
                var topics = ViewAll().ToList();
                dynamic models = new ExpandoObject();
                models.Trainers = trainers;
                models.Courses = courses;
                models.Topics = topics;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Topic/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                if (topic == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Description,Trainer,Course")] Topic topic, int courseId, int trainerId)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    topic.Trainer = this.context.Trainers.ToList().Find(item => item.Id == trainerId);
                    topic.Course = this.context.Courses.ToList().Find(item => item.Id == courseId);
                    AddNew(topic);
                    return RedirectToAction(nameof(Index));
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Topic/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                var trainers = context.Trainers.ToList();
                var courses = context.Courses.ToList();
                if (topic == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                dynamic models = new ExpandoObject();
                models.Trainers = trainers;
                models.Courses = courses;
                models.Topic = topic;
                return View(models);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Topic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description,Trainer,Course")] Topic topic, int courseId, int trainerId)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (id != topic.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        topic.Course = context.Courses.ToList().Find(item => item.Id == courseId);
                        topic.Trainer = context.Trainers.ToList().Find(item => item.Id == trainerId);
                        EditModel(topic);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TraineeExists(topic.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Topic/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                if (topic == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(topic);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Topic/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var topic = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool TraineeExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Controllers/TraineesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AcademicManagement.Data;
using AcademicManagement.Models;
using AcademicManagement.FactoryMethod;

namespace AcademicManagement.Controllers
{
    public class TraineesController : TraineesFactory
    {
        public TraineesController(AcademicContext context) : base(context) {
            base.context = context;
        }

        // GET: Trainees
        public IActionResult Index([FromQuery(Name = "name")] string name)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if(name == null)
                {
                    return View(ViewAll().ToList());
                }
                else
                {
                    return View(SearchByName(name));
                }
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainees/Details/5
        public IActionResult Details(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Id,Name,Age,Email,Password,Telephone,DateOfBirth,Education,MainProgrammingLanguage,TOEICScore,ExperienceDetails,Department,Location")] Trainee trainee)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (ModelState.IsValid)
                {
                    AddNew(trainee);
                    return RedirectToAction(nameof(Index));
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainees/Edit/5
        public IActionResult Edit(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Trainees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Age,DateOfBirth,Education,MainProgrammingLanguage,TOEICScore,ExperienceDetails,Department,Location,Id,Email,Password,Name,Telephone")] Trainee trainee)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                if (id != trainee.Id)
                {
                    return RedirectToAction("Index", "NotFound");
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        EditModel(trainee);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TraineeExists(trainee.Id))
                        {
                            return RedirectToAction("Index", "NotFound");
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // GET: Trainees/Delete/5
        public IActionResult Delete(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                if (trainee == null)
                {
                    return RedirectToAction("Index", "NotFound");
                }
                return View(trainee);
            }
            return RedirectToAction("Index", "NotFound");
        }

        // POST: Trainees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (UserSingleton.getIntance().Role == new Staff().GetType().Name)
            {
                var trainee = SearchById(id);
                DeleteModel(id);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction("Index", "NotFound");
        }

        private bool TraineeExists(int id)
        {
            return (SearchById(id) != null);
        }
    }
}

Views/Topics/Delete.cshtml
@model AcademicManagement.Models.Topic

@{
    ViewData["Title"] = "Topics Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <div class="card">
        <div class="card-body">
            <div class="modal-body row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>            
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Trainer.Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Email</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Course.Name" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Course</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" asp-for="Description" class="form-control pl-4" id="floatingInput" disabled>
                        <label for="floatingInput" class="ml-5">Description</label>
                    </div>
                </div>             
            </div>
            <div class="modal-footer">
                <form asp-action="Delete">
                    <input type="hidden" asp-for="Id" />
                    <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

Views/Topics/Details.cshtml
@model AcademicManagement.Models.Topic

@{
    ViewData["Title"] = "Topics Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Topic</h4>
    <hr />
    <div>
        <div class="card">
            <div class="card-body">
                <div class="modal-body row">
                    <div class="col">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Name" class="form-control pl-4" id="floatingInput" disabled>
                            <label for="floatingInput" class="ml-5">Full name</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Trainer.Name" class="form-control pl-4" id="floatingInput" disabled>
                            <label for="floatingInput" class="ml-5">Trainer</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Course.Name" class="form-control pl-4" id="floatingInput" disabled>
                            <label for="floatingInput" class="ml-5">Course</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" asp-for="Description" class="form-control pl-4" id="floatingInput" disabled>
                            <label for="floatingInput" class="ml-5">Description</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Topics/Edit.cshtml
@using System.Dynamic;
@model dynamic;

@{
    ViewData["Title"] = "Topics Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Staff</h4>
<hr />
<div class="card">
    <div class="card-body">
        <form method="post" asp-action="Edit" asp-controller="Topics">
            <div class="modal-body row">
                <div class="col">
                    <div class="form-floating mb-3">
                        <input type="text" name="Name" value="@Model.Topic.Name" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Full name</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <select class="form-select" name="trainerId" id="floatingSelectGrid" aria-label="Floating label select example">
                            @foreach (Trainer trainer in Model.Trainers)
                            {
                                @if (Model.Topic.Trainer.Id == trainer.Id)
                                {
                                    <option value="@trainer.Id" selected>@trainer.Name</option>
                                }
                                else
                                {
                                    <option value="@trainer.Id">@trainer.Name</option>
                                }
                            }
                        </select>
                        <label for="floatingSelectGrid">Trainer</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <select class="form-select" name="courseId" id="floatingSelectGrid" aria-label="Floating label select example">
                            @foreach (Course course in Model.Courses)
                            {
                                @if (Model.Topic.Course.Id == course.Id)
                                {
                                    <option value="@course.Id" selected>@course.Name</option>
                                }
                                else
                                {
                                    <option value="@course.Id">@course.Name</option>
                                }
                            }
                        </select>
                        <label for="floatingSelectGrid">Course</label>
                    </div>
                </div>
                <div class="">
                    <div class="form-floating mb-3">
                        <input type="text" name="Description" value="@Model.Topic.Description" class="form-control pl-4" id="floatingInput">
                        <label for="floatingInput" class="ml-5">Description</label>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <a asp-action="Index" class="btn btn-secondary">Back to list</a>
                <input type="submit" class="btn btn-primary" value="Save" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Topics/Index.cshtml
@using System.Dynamic;
@model dynamic;

@{
    ViewData["Title"] = "Topics Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="margin-horizontal">
    <a class="link-secondary bold h4" asp-action="Index" asp-controller="Trainers">Trainer</a>
    <a class="link-secondary bold margin-left h4" asp-action="Index" asp-controller="Trainees">Trainee</a>
    <a class="link-primary bold margin-left h4" asp-action="Index" asp-controller="Courses">Course</a>
</div>

<div class="margin-horizontal">
    <a class="link-primary bold h5" asp-action="Index" asp-controller="Topics">Topics</a>
    <a class="link-secondary bold margin-left h5" asp-action="Index" asp-controller="Categories">Categories</a>
</div>

<h1>Management Topic</h1>

<a class="link-primary pointer pointer"
   data-bs-toggle="modal"
   data-bs-target="#createNewTopic">
    Create new topic
</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Id")
            </th>
            <th>
                @Html.DisplayName("Name")
            </th>
            <th>
                @Html.DisplayName("Trainer")
            </th>

            <th>
                @Html.DisplayName("Course")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (Topic item in Model.Topics)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trainer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade" id="createNewTopic" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Create new topic account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" asp-action="Index" asp-controller="Topics">
                <div class="modal-body row">
                    <div class="col">
                        <div class="form-floating mb-3">
                            <input type="text" name="Name" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Full name</label>
                        </div>
                    </div>

                    <div class="">
                        <div class="form-floating mb-3">
                            <select class="form-select" name="trainerId" id="floatingSelectGrid" aria-label="Floating label select example">
                                @foreach (Trainer trainer in Model.Trainers)
                                {
                                    <option value="@trainer.Id">@trainer.Name</option>
                                }
                            </select>
                            <label for="floatingSelectGrid">Trainer</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <select class="form-select" name="courseId" id="floatingSelectGrid" aria-label="Floating label select example">
                                @foreach (Course course in Model.Courses)
                                {
                                    <option value="@course.Id">@course.Name</option>
                                }
                            </select>
                            <label for="floatingSelectGrid">Course</label>
                        </div>
                    </div>
                    <div class="">
                        <div class="form-floating mb-3">
                            <input type="text" name="Description" class="form-control pl-4" id="floatingInput">
                            <label for="floatingInput" class="ml-5">Description</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Create" />
                </div>
            </form>
        </div>
    </div>
</div>